"""Comprehensive automotive parts catalog for synthetic warranty claim generation.

Contains 200+ part entries organized by vehicle system, each with realistic
OEM pricing, labor time estimates, typical failure mileage ranges, and
wear-item classification. Pricing reflects 2024-2025 era OEM part costs.

Sources:
    - RepairPal cost estimates (2024-2025)
    - NAPA, AutoZone, and OEM dealer parts pricing
    - ALLDATA and Mitchell labor time guides
    - J.D. Power and Consumer Reports repair cost data
"""

from typing import TypedDict


class PartEntry(TypedDict):
    """Schema for a parts catalog entry."""

    name: str
    category: str
    subcategory: str
    price_range: tuple[float, float]        # (min_price, max_price) OEM $
    typical_labor_hours: float               # book time for replacement
    common_failure_mileage_range: tuple[int, int]  # (min_miles, max_miles)
    is_wear_item: bool                       # expected to wear out in service


# ---------------------------------------------------------------------------
# Parts catalog  (200+ entries)
# ---------------------------------------------------------------------------

PARTS: list[PartEntry] = [

    # ======================================================================
    # ENGINE  --  Internal Components
    # ======================================================================
    {
        "name": "Head Gasket",
        "category": "Engine",
        "subcategory": "Gaskets & Seals",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 8.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Valve Cover Gasket",
        "category": "Engine",
        "subcategory": "Gaskets & Seals",
        "price_range": (25.00, 120.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (60_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Intake Manifold Gasket",
        "category": "Engine",
        "subcategory": "Gaskets & Seals",
        "price_range": (30.00, 150.00),
        "typical_labor_hours": 3.5,
        "common_failure_mileage_range": (70_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Oil Pan Gasket",
        "category": "Engine",
        "subcategory": "Gaskets & Seals",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 3.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Exhaust Manifold Gasket",
        "category": "Engine",
        "subcategory": "Gaskets & Seals",
        "price_range": (20.00, 60.00),
        "typical_labor_hours": 2.5,
        "common_failure_mileage_range": (70_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Rear Main Seal",
        "category": "Engine",
        "subcategory": "Gaskets & Seals",
        "price_range": (25.00, 80.00),
        "typical_labor_hours": 6.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Front Crankshaft Seal",
        "category": "Engine",
        "subcategory": "Gaskets & Seals",
        "price_range": (15.00, 45.00),
        "typical_labor_hours": 3.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Timing Chain",
        "category": "Engine",
        "subcategory": "Timing",
        "price_range": (150.00, 600.00),
        "typical_labor_hours": 6.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Timing Chain Tensioner",
        "category": "Engine",
        "subcategory": "Timing",
        "price_range": (40.00, 180.00),
        "typical_labor_hours": 5.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Timing Chain Guide",
        "category": "Engine",
        "subcategory": "Timing",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 5.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Timing Belt",
        "category": "Engine",
        "subcategory": "Timing",
        "price_range": (35.00, 120.00),
        "typical_labor_hours": 4.5,
        "common_failure_mileage_range": (60_000, 105_000),
        "is_wear_item": True,
    },
    {
        "name": "Timing Belt Tensioner",
        "category": "Engine",
        "subcategory": "Timing",
        "price_range": (40.00, 150.00),
        "typical_labor_hours": 4.5,
        "common_failure_mileage_range": (60_000, 105_000),
        "is_wear_item": True,
    },
    {
        "name": "Serpentine Belt",
        "category": "Engine",
        "subcategory": "Belts & Pulleys",
        "price_range": (25.00, 70.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (50_000, 100_000),
        "is_wear_item": True,
    },
    {
        "name": "Belt Tensioner Assembly",
        "category": "Engine",
        "subcategory": "Belts & Pulleys",
        "price_range": (60.00, 180.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Idler Pulley",
        "category": "Engine",
        "subcategory": "Belts & Pulleys",
        "price_range": (20.00, 60.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Engine Mount",
        "category": "Engine",
        "subcategory": "Mounts",
        "price_range": (50.00, 250.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Transmission Mount",
        "category": "Engine",
        "subcategory": "Mounts",
        "price_range": (40.00, 180.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "PCV Valve",
        "category": "Engine",
        "subcategory": "Emission/Ventilation",
        "price_range": (10.00, 40.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (50_000, 100_000),
        "is_wear_item": True,
    },

    # ======================================================================
    # ENGINE  --  Sensors
    # ======================================================================
    {
        "name": "Oxygen Sensor (O2 Sensor)",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (60.00, 250.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": True,
    },
    {
        "name": "Mass Air Flow Sensor (MAF)",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Throttle Position Sensor (TPS)",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (40.00, 200.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (70_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Camshaft Position Sensor",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (30.00, 150.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Crankshaft Position Sensor",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (30.00, 150.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Coolant Temperature Sensor",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (15.00, 60.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (70_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Oil Pressure Sensor",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (15.00, 80.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Knock Sensor",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "MAP Sensor",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (70_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Intake Air Temperature Sensor",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (15.00, 60.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Variable Valve Timing Solenoid",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (40.00, 180.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (70_000, 140_000),
        "is_wear_item": False,
    },

    # ======================================================================
    # ENGINE  --  Pumps & Mechanical
    # ======================================================================
    {
        "name": "Water Pump",
        "category": "Engine",
        "subcategory": "Pumps",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 3.0,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": False,
    },
    {
        "name": "Oil Pump",
        "category": "Engine",
        "subcategory": "Pumps",
        "price_range": (100.00, 400.00),
        "typical_labor_hours": 6.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Turbocharger",
        "category": "Engine",
        "subcategory": "Forced Induction",
        "price_range": (600.00, 2_500.00),
        "typical_labor_hours": 5.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Turbo Wastegate Actuator",
        "category": "Engine",
        "subcategory": "Forced Induction",
        "price_range": (80.00, 300.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Intercooler",
        "category": "Engine",
        "subcategory": "Forced Induction",
        "price_range": (200.00, 800.00),
        "typical_labor_hours": 2.5,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },

    # ======================================================================
    # ENGINE  --  Ignition
    # ======================================================================
    {
        "name": "Spark Plug (each)",
        "category": "Engine",
        "subcategory": "Ignition",
        "price_range": (6.00, 25.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (30_000, 100_000),
        "is_wear_item": True,
    },
    {
        "name": "Ignition Coil",
        "category": "Engine",
        "subcategory": "Ignition",
        "price_range": (35.00, 120.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Ignition Coil Pack (set)",
        "category": "Engine",
        "subcategory": "Ignition",
        "price_range": (150.00, 400.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Spark Plug Wires (set)",
        "category": "Engine",
        "subcategory": "Ignition",
        "price_range": (30.00, 100.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (50_000, 100_000),
        "is_wear_item": True,
    },

    # ======================================================================
    # BRAKE SYSTEM
    # ======================================================================
    {
        "name": "Front Brake Pads (set)",
        "category": "Brakes",
        "subcategory": "Pads",
        "price_range": (40.00, 150.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (25_000, 65_000),
        "is_wear_item": True,
    },
    {
        "name": "Rear Brake Pads (set)",
        "category": "Brakes",
        "subcategory": "Pads",
        "price_range": (35.00, 130.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (30_000, 75_000),
        "is_wear_item": True,
    },
    {
        "name": "Front Brake Rotor (each)",
        "category": "Brakes",
        "subcategory": "Rotors",
        "price_range": (50.00, 200.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (40_000, 80_000),
        "is_wear_item": True,
    },
    {
        "name": "Rear Brake Rotor (each)",
        "category": "Brakes",
        "subcategory": "Rotors",
        "price_range": (45.00, 180.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (50_000, 90_000),
        "is_wear_item": True,
    },
    {
        "name": "Brake Caliper",
        "category": "Brakes",
        "subcategory": "Calipers",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 1.2,
        "common_failure_mileage_range": (75_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Brake Caliper Bracket",
        "category": "Brakes",
        "subcategory": "Calipers",
        "price_range": (40.00, 120.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Brake Master Cylinder",
        "category": "Brakes",
        "subcategory": "Hydraulic",
        "price_range": (100.00, 350.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Brake Booster",
        "category": "Brakes",
        "subcategory": "Hydraulic",
        "price_range": (150.00, 500.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Brake Line (each)",
        "category": "Brakes",
        "subcategory": "Hydraulic",
        "price_range": (15.00, 60.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Brake Hose (each)",
        "category": "Brakes",
        "subcategory": "Hydraulic",
        "price_range": (20.00, 70.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "ABS Wheel Speed Sensor",
        "category": "Brakes",
        "subcategory": "ABS",
        "price_range": (30.00, 150.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "ABS Module",
        "category": "Brakes",
        "subcategory": "ABS",
        "price_range": (300.00, 1_200.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Parking Brake Cable",
        "category": "Brakes",
        "subcategory": "Parking Brake",
        "price_range": (25.00, 80.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": True,
    },
    {
        "name": "Parking Brake Shoes",
        "category": "Brakes",
        "subcategory": "Parking Brake",
        "price_range": (20.00, 60.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Brake Fluid Flush",
        "category": "Brakes",
        "subcategory": "Fluid",
        "price_range": (15.00, 30.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (30_000, 60_000),
        "is_wear_item": True,
    },

    # ======================================================================
    # SUSPENSION
    # ======================================================================
    {
        "name": "Front Strut Assembly",
        "category": "Suspension",
        "subcategory": "Struts & Shocks",
        "price_range": (120.00, 450.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Rear Shock Absorber",
        "category": "Suspension",
        "subcategory": "Struts & Shocks",
        "price_range": (60.00, 250.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Front Strut Mount",
        "category": "Suspension",
        "subcategory": "Struts & Shocks",
        "price_range": (40.00, 120.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Front Lower Control Arm",
        "category": "Suspension",
        "subcategory": "Control Arms",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (70_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Front Upper Control Arm",
        "category": "Suspension",
        "subcategory": "Control Arms",
        "price_range": (70.00, 300.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (70_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Rear Control Arm",
        "category": "Suspension",
        "subcategory": "Control Arms",
        "price_range": (60.00, 250.00),
        "typical_labor_hours": 1.2,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Ball Joint (each)",
        "category": "Suspension",
        "subcategory": "Joints & Bushings",
        "price_range": (30.00, 150.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": True,
    },
    {
        "name": "Front Sway Bar Link",
        "category": "Suspension",
        "subcategory": "Sway Bar",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (40_000, 100_000),
        "is_wear_item": True,
    },
    {
        "name": "Rear Sway Bar Link",
        "category": "Suspension",
        "subcategory": "Sway Bar",
        "price_range": (20.00, 70.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (40_000, 100_000),
        "is_wear_item": True,
    },
    {
        "name": "Sway Bar Bushing (pair)",
        "category": "Suspension",
        "subcategory": "Sway Bar",
        "price_range": (10.00, 40.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (50_000, 100_000),
        "is_wear_item": True,
    },
    {
        "name": "Front Wheel Bearing/Hub Assembly",
        "category": "Suspension",
        "subcategory": "Bearings",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 1.8,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": False,
    },
    {
        "name": "Rear Wheel Bearing/Hub Assembly",
        "category": "Suspension",
        "subcategory": "Bearings",
        "price_range": (70.00, 300.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (70_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Front Coil Spring",
        "category": "Suspension",
        "subcategory": "Springs",
        "price_range": (60.00, 200.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Rear Coil Spring",
        "category": "Suspension",
        "subcategory": "Springs",
        "price_range": (50.00, 180.00),
        "typical_labor_hours": 1.2,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Leaf Spring (each)",
        "category": "Suspension",
        "subcategory": "Springs",
        "price_range": (100.00, 400.00),
        "typical_labor_hours": 2.5,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Control Arm Bushing",
        "category": "Suspension",
        "subcategory": "Joints & Bushings",
        "price_range": (15.00, 80.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": True,
    },
    {
        "name": "Trailing Arm Bushing",
        "category": "Suspension",
        "subcategory": "Joints & Bushings",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (70_000, 140_000),
        "is_wear_item": True,
    },

    # ======================================================================
    # ELECTRICAL
    # ======================================================================
    {
        "name": "Alternator",
        "category": "Electrical",
        "subcategory": "Charging",
        "price_range": (200.00, 650.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Starter Motor",
        "category": "Electrical",
        "subcategory": "Starting",
        "price_range": (150.00, 500.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Battery",
        "category": "Electrical",
        "subcategory": "Charging",
        "price_range": (100.00, 300.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (36_000, 80_000),
        "is_wear_item": True,
    },
    {
        "name": "Voltage Regulator",
        "category": "Electrical",
        "subcategory": "Charging",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "ECU / ECM (Engine Control Module)",
        "category": "Electrical",
        "subcategory": "Modules",
        "price_range": (400.00, 1_800.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "TCM (Transmission Control Module)",
        "category": "Electrical",
        "subcategory": "Modules",
        "price_range": (300.00, 1_200.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "BCM (Body Control Module)",
        "category": "Electrical",
        "subcategory": "Modules",
        "price_range": (200.00, 800.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Instrument Cluster",
        "category": "Electrical",
        "subcategory": "Modules",
        "price_range": (250.00, 1_000.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Headlight Assembly",
        "category": "Electrical",
        "subcategory": "Lighting",
        "price_range": (100.00, 800.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (60_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Tail Light Assembly",
        "category": "Electrical",
        "subcategory": "Lighting",
        "price_range": (80.00, 400.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Headlight Bulb",
        "category": "Electrical",
        "subcategory": "Lighting",
        "price_range": (10.00, 80.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (30_000, 80_000),
        "is_wear_item": True,
    },
    {
        "name": "Power Window Motor",
        "category": "Electrical",
        "subcategory": "Power Accessories",
        "price_range": (60.00, 250.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Power Window Regulator",
        "category": "Electrical",
        "subcategory": "Power Accessories",
        "price_range": (50.00, 200.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Door Lock Actuator",
        "category": "Electrical",
        "subcategory": "Power Accessories",
        "price_range": (40.00, 180.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Wiper Motor",
        "category": "Electrical",
        "subcategory": "Wipers",
        "price_range": (60.00, 250.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Wiper Linkage",
        "category": "Electrical",
        "subcategory": "Wipers",
        "price_range": (40.00, 150.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Blower Motor Resistor",
        "category": "Electrical",
        "subcategory": "HVAC Controls",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Horn",
        "category": "Electrical",
        "subcategory": "Accessories",
        "price_range": (20.00, 60.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (80_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Fuse Box / Power Distribution Center",
        "category": "Electrical",
        "subcategory": "Wiring",
        "price_range": (100.00, 400.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Ignition Switch",
        "category": "Electrical",
        "subcategory": "Starting",
        "price_range": (40.00, 200.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Backup Camera",
        "category": "Electrical",
        "subcategory": "Safety Electronics",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "TPMS Sensor (each)",
        "category": "Electrical",
        "subcategory": "Safety Electronics",
        "price_range": (30.00, 100.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (40_000, 100_000),
        "is_wear_item": True,
    },

    # ======================================================================
    # HVAC  (Heating, Ventilation, Air Conditioning)
    # ======================================================================
    {
        "name": "AC Compressor",
        "category": "HVAC",
        "subcategory": "Air Conditioning",
        "price_range": (250.00, 800.00),
        "typical_labor_hours": 3.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "AC Condenser",
        "category": "HVAC",
        "subcategory": "Air Conditioning",
        "price_range": (150.00, 500.00),
        "typical_labor_hours": 2.5,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "AC Evaporator",
        "category": "HVAC",
        "subcategory": "Air Conditioning",
        "price_range": (200.00, 600.00),
        "typical_labor_hours": 6.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "AC Expansion Valve",
        "category": "HVAC",
        "subcategory": "Air Conditioning",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "AC Receiver Drier / Accumulator",
        "category": "HVAC",
        "subcategory": "Air Conditioning",
        "price_range": (30.00, 100.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "AC Refrigerant (R-134a/R-1234yf)",
        "category": "HVAC",
        "subcategory": "Air Conditioning",
        "price_range": (30.00, 80.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (40_000, 100_000),
        "is_wear_item": True,
    },
    {
        "name": "Blower Motor",
        "category": "HVAC",
        "subcategory": "Ventilation",
        "price_range": (60.00, 250.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Heater Core",
        "category": "HVAC",
        "subcategory": "Heating",
        "price_range": (80.00, 300.00),
        "typical_labor_hours": 6.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Heater Control Valve",
        "category": "HVAC",
        "subcategory": "Heating",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Cabin Air Filter",
        "category": "HVAC",
        "subcategory": "Filtration",
        "price_range": (15.00, 40.00),
        "typical_labor_hours": 0.2,
        "common_failure_mileage_range": (12_000, 30_000),
        "is_wear_item": True,
    },
    {
        "name": "Blend Door Actuator",
        "category": "HVAC",
        "subcategory": "Controls",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "HVAC Mode Door Actuator",
        "category": "HVAC",
        "subcategory": "Controls",
        "price_range": (30.00, 100.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },

    # ======================================================================
    # TRANSMISSION
    # ======================================================================
    {
        "name": "Automatic Transmission Assembly",
        "category": "Transmission",
        "subcategory": "Complete Unit",
        "price_range": (2_000.00, 6_000.00),
        "typical_labor_hours": 8.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "CVT Transmission Assembly",
        "category": "Transmission",
        "subcategory": "Complete Unit",
        "price_range": (2_500.00, 5_500.00),
        "typical_labor_hours": 8.0,
        "common_failure_mileage_range": (80_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Torque Converter",
        "category": "Transmission",
        "subcategory": "Internal Components",
        "price_range": (150.00, 500.00),
        "typical_labor_hours": 6.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Transmission Solenoid Pack",
        "category": "Transmission",
        "subcategory": "Internal Components",
        "price_range": (80.00, 400.00),
        "typical_labor_hours": 3.0,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Shift Solenoid (each)",
        "category": "Transmission",
        "subcategory": "Internal Components",
        "price_range": (30.00, 150.00),
        "typical_labor_hours": 2.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Transmission Filter & Gasket Kit",
        "category": "Transmission",
        "subcategory": "Maintenance",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (30_000, 60_000),
        "is_wear_item": True,
    },
    {
        "name": "Transmission Fluid (full service)",
        "category": "Transmission",
        "subcategory": "Maintenance",
        "price_range": (40.00, 120.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (30_000, 60_000),
        "is_wear_item": True,
    },
    {
        "name": "Clutch Kit (manual)",
        "category": "Transmission",
        "subcategory": "Manual Transmission",
        "price_range": (150.00, 500.00),
        "typical_labor_hours": 5.0,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": True,
    },
    {
        "name": "Flywheel / Dual-Mass Flywheel",
        "category": "Transmission",
        "subcategory": "Manual Transmission",
        "price_range": (200.00, 800.00),
        "typical_labor_hours": 5.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Clutch Master Cylinder",
        "category": "Transmission",
        "subcategory": "Manual Transmission",
        "price_range": (40.00, 150.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (70_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Clutch Slave Cylinder",
        "category": "Transmission",
        "subcategory": "Manual Transmission",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": False,
    },
    {
        "name": "Transmission Speed Sensor",
        "category": "Transmission",
        "subcategory": "Sensors",
        "price_range": (20.00, 100.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Transmission Range Sensor",
        "category": "Transmission",
        "subcategory": "Sensors",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (70_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "CV Axle / Half Shaft",
        "category": "Transmission",
        "subcategory": "Drivetrain",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "CV Boot (inner or outer)",
        "category": "Transmission",
        "subcategory": "Drivetrain",
        "price_range": (20.00, 60.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": True,
    },
    {
        "name": "U-Joint",
        "category": "Transmission",
        "subcategory": "Drivetrain",
        "price_range": (15.00, 50.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": True,
    },
    {
        "name": "Driveshaft",
        "category": "Transmission",
        "subcategory": "Drivetrain",
        "price_range": (200.00, 800.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Transfer Case",
        "category": "Transmission",
        "subcategory": "Drivetrain",
        "price_range": (800.00, 2_500.00),
        "typical_labor_hours": 5.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Differential Assembly (rear)",
        "category": "Transmission",
        "subcategory": "Drivetrain",
        "price_range": (500.00, 2_000.00),
        "typical_labor_hours": 4.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },

    # ======================================================================
    # EXHAUST & EMISSIONS
    # ======================================================================
    {
        "name": "Catalytic Converter",
        "category": "Exhaust",
        "subcategory": "Emissions",
        "price_range": (300.00, 2_500.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Muffler",
        "category": "Exhaust",
        "subcategory": "Exhaust System",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": True,
    },
    {
        "name": "Exhaust Pipe Section",
        "category": "Exhaust",
        "subcategory": "Exhaust System",
        "price_range": (40.00, 200.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": True,
    },
    {
        "name": "Exhaust Manifold",
        "category": "Exhaust",
        "subcategory": "Exhaust System",
        "price_range": (100.00, 500.00),
        "typical_labor_hours": 2.5,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Exhaust Flex Pipe",
        "category": "Exhaust",
        "subcategory": "Exhaust System",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": True,
    },
    {
        "name": "Exhaust Resonator",
        "category": "Exhaust",
        "subcategory": "Exhaust System",
        "price_range": (60.00, 200.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": True,
    },
    {
        "name": "EGR Valve",
        "category": "Exhaust",
        "subcategory": "Emissions",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": False,
    },
    {
        "name": "EVAP Purge Valve",
        "category": "Exhaust",
        "subcategory": "Emissions",
        "price_range": (25.00, 100.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "EVAP Charcoal Canister",
        "category": "Exhaust",
        "subcategory": "Emissions",
        "price_range": (80.00, 300.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "EVAP Vent Valve",
        "category": "Exhaust",
        "subcategory": "Emissions",
        "price_range": (30.00, 100.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "DPF (Diesel Particulate Filter)",
        "category": "Exhaust",
        "subcategory": "Emissions",
        "price_range": (800.00, 3_000.00),
        "typical_labor_hours": 2.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "DEF Injector (diesel)",
        "category": "Exhaust",
        "subcategory": "Emissions",
        "price_range": (80.00, 250.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },

    # ======================================================================
    # STEERING
    # ======================================================================
    {
        "name": "Power Steering Pump",
        "category": "Steering",
        "subcategory": "Hydraulic Steering",
        "price_range": (100.00, 400.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Power Steering Rack & Pinion",
        "category": "Steering",
        "subcategory": "Steering Gear",
        "price_range": (300.00, 1_200.00),
        "typical_labor_hours": 3.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Electric Power Steering Motor",
        "category": "Steering",
        "subcategory": "Electric Steering",
        "price_range": (250.00, 900.00),
        "typical_labor_hours": 2.5,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Steering Column",
        "category": "Steering",
        "subcategory": "Column",
        "price_range": (200.00, 800.00),
        "typical_labor_hours": 3.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Tie Rod End (inner)",
        "category": "Steering",
        "subcategory": "Linkage",
        "price_range": (25.00, 100.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": True,
    },
    {
        "name": "Tie Rod End (outer)",
        "category": "Steering",
        "subcategory": "Linkage",
        "price_range": (25.00, 90.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (50_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Power Steering Pressure Hose",
        "category": "Steering",
        "subcategory": "Hydraulic Steering",
        "price_range": (40.00, 150.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Power Steering Return Hose",
        "category": "Steering",
        "subcategory": "Hydraulic Steering",
        "price_range": (25.00, 80.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Power Steering Fluid Reservoir",
        "category": "Steering",
        "subcategory": "Hydraulic Steering",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Intermediate Steering Shaft",
        "category": "Steering",
        "subcategory": "Column",
        "price_range": (60.00, 250.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Pitman Arm",
        "category": "Steering",
        "subcategory": "Linkage",
        "price_range": (40.00, 150.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": True,
    },
    {
        "name": "Idler Arm",
        "category": "Steering",
        "subcategory": "Linkage",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (70_000, 150_000),
        "is_wear_item": True,
    },
    {
        "name": "Center Link / Drag Link",
        "category": "Steering",
        "subcategory": "Linkage",
        "price_range": (50.00, 200.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": True,
    },

    # ======================================================================
    # COOLING SYSTEM
    # ======================================================================
    {
        "name": "Radiator",
        "category": "Cooling",
        "subcategory": "Heat Exchange",
        "price_range": (150.00, 500.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Radiator Hose (upper)",
        "category": "Cooling",
        "subcategory": "Hoses",
        "price_range": (20.00, 60.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Radiator Hose (lower)",
        "category": "Cooling",
        "subcategory": "Hoses",
        "price_range": (20.00, 60.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Thermostat",
        "category": "Cooling",
        "subcategory": "Temperature Control",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": False,
    },
    {
        "name": "Thermostat Housing",
        "category": "Cooling",
        "subcategory": "Temperature Control",
        "price_range": (30.00, 150.00),
        "typical_labor_hours": 1.2,
        "common_failure_mileage_range": (60_000, 130_000),
        "is_wear_item": False,
    },
    {
        "name": "Radiator Fan Motor",
        "category": "Cooling",
        "subcategory": "Fans",
        "price_range": (80.00, 350.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Radiator Fan Assembly",
        "category": "Cooling",
        "subcategory": "Fans",
        "price_range": (150.00, 500.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Fan Clutch",
        "category": "Cooling",
        "subcategory": "Fans",
        "price_range": (60.00, 200.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Coolant Reservoir / Expansion Tank",
        "category": "Cooling",
        "subcategory": "Reservoir",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Coolant (per gallon)",
        "category": "Cooling",
        "subcategory": "Fluid",
        "price_range": (12.00, 30.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (30_000, 60_000),
        "is_wear_item": True,
    },
    {
        "name": "Heater Hose",
        "category": "Cooling",
        "subcategory": "Hoses",
        "price_range": (15.00, 50.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Radiator Cap",
        "category": "Cooling",
        "subcategory": "Caps & Seals",
        "price_range": (8.00, 25.00),
        "typical_labor_hours": 0.1,
        "common_failure_mileage_range": (50_000, 100_000),
        "is_wear_item": True,
    },
    {
        "name": "Coolant Temperature Sensor",
        "category": "Cooling",
        "subcategory": "Sensors",
        "price_range": (15.00, 60.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (70_000, 150_000),
        "is_wear_item": False,
    },

    # ======================================================================
    # FUEL SYSTEM
    # ======================================================================
    {
        "name": "Fuel Pump Assembly",
        "category": "Fuel System",
        "subcategory": "Fuel Delivery",
        "price_range": (200.00, 700.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "High-Pressure Fuel Pump (GDI)",
        "category": "Fuel System",
        "subcategory": "Fuel Delivery",
        "price_range": (250.00, 800.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },
    {
        "name": "Fuel Injector (each)",
        "category": "Fuel System",
        "subcategory": "Fuel Delivery",
        "price_range": (50.00, 250.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Fuel Injector Set (4-cylinder)",
        "category": "Fuel System",
        "subcategory": "Fuel Delivery",
        "price_range": (200.00, 800.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Fuel Filter",
        "category": "Fuel System",
        "subcategory": "Filtration",
        "price_range": (15.00, 60.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (30_000, 60_000),
        "is_wear_item": True,
    },
    {
        "name": "Fuel Pressure Regulator",
        "category": "Fuel System",
        "subcategory": "Fuel Delivery",
        "price_range": (40.00, 180.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Fuel Tank",
        "category": "Fuel System",
        "subcategory": "Storage",
        "price_range": (250.00, 800.00),
        "typical_labor_hours": 3.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Fuel Filler Neck",
        "category": "Fuel System",
        "subcategory": "Storage",
        "price_range": (40.00, 150.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Fuel Rail",
        "category": "Fuel System",
        "subcategory": "Fuel Delivery",
        "price_range": (80.00, 300.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Fuel Level Sensor / Sending Unit",
        "category": "Fuel System",
        "subcategory": "Sensors",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Throttle Body",
        "category": "Fuel System",
        "subcategory": "Air Intake",
        "price_range": (100.00, 450.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Intake Manifold",
        "category": "Fuel System",
        "subcategory": "Air Intake",
        "price_range": (150.00, 600.00),
        "typical_labor_hours": 3.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Engine Air Filter",
        "category": "Fuel System",
        "subcategory": "Filtration",
        "price_range": (15.00, 40.00),
        "typical_labor_hours": 0.1,
        "common_failure_mileage_range": (12_000, 30_000),
        "is_wear_item": True,
    },
    {
        "name": "Air Intake Boot / Duct",
        "category": "Fuel System",
        "subcategory": "Air Intake",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (60_000, 140_000),
        "is_wear_item": False,
    },

    # ======================================================================
    # BODY & MISCELLANEOUS
    # ======================================================================
    {
        "name": "Side Mirror Assembly",
        "category": "Body",
        "subcategory": "Mirrors",
        "price_range": (80.00, 450.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (40_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Door Handle (exterior)",
        "category": "Body",
        "subcategory": "Handles",
        "price_range": (30.00, 150.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (60_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Door Handle (interior)",
        "category": "Body",
        "subcategory": "Handles",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Hood Latch",
        "category": "Body",
        "subcategory": "Latches",
        "price_range": (25.00, 80.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (80_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Trunk/Liftgate Latch",
        "category": "Body",
        "subcategory": "Latches",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (80_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Liftgate Strut (each)",
        "category": "Body",
        "subcategory": "Supports",
        "price_range": (15.00, 60.00),
        "typical_labor_hours": 0.2,
        "common_failure_mileage_range": (50_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Hood Strut (each)",
        "category": "Body",
        "subcategory": "Supports",
        "price_range": (15.00, 50.00),
        "typical_labor_hours": 0.2,
        "common_failure_mileage_range": (50_000, 120_000),
        "is_wear_item": True,
    },
    {
        "name": "Windshield Washer Pump",
        "category": "Body",
        "subcategory": "Wipers & Washers",
        "price_range": (15.00, 50.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (60_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Windshield Washer Reservoir",
        "category": "Body",
        "subcategory": "Wipers & Washers",
        "price_range": (20.00, 60.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (80_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Wheel Stud (each)",
        "category": "Body",
        "subcategory": "Wheels",
        "price_range": (3.00, 10.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (60_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Lug Nut (each)",
        "category": "Body",
        "subcategory": "Wheels",
        "price_range": (2.00, 8.00),
        "typical_labor_hours": 0.1,
        "common_failure_mileage_range": (60_000, 200_000),
        "is_wear_item": False,
    },

    # ======================================================================
    # ADDITIONAL ENGINE PARTS
    # ======================================================================
    {
        "name": "Engine Oil Filter",
        "category": "Engine",
        "subcategory": "Filtration",
        "price_range": (6.00, 20.00),
        "typical_labor_hours": 0.1,
        "common_failure_mileage_range": (5_000, 10_000),
        "is_wear_item": True,
    },
    {
        "name": "Engine Oil (5 quarts conventional)",
        "category": "Engine",
        "subcategory": "Fluids",
        "price_range": (20.00, 35.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (5_000, 10_000),
        "is_wear_item": True,
    },
    {
        "name": "Engine Oil (full synthetic, 5 quarts)",
        "category": "Engine",
        "subcategory": "Fluids",
        "price_range": (30.00, 55.00),
        "typical_labor_hours": 0.3,
        "common_failure_mileage_range": (7_500, 15_000),
        "is_wear_item": True,
    },
    {
        "name": "Camshaft Phaser / VVT Gear",
        "category": "Engine",
        "subcategory": "Timing",
        "price_range": (100.00, 400.00),
        "typical_labor_hours": 4.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Intake Valve (each)",
        "category": "Engine",
        "subcategory": "Valvetrain",
        "price_range": (15.00, 60.00),
        "typical_labor_hours": 8.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Exhaust Valve (each)",
        "category": "Engine",
        "subcategory": "Valvetrain",
        "price_range": (15.00, 60.00),
        "typical_labor_hours": 8.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Valve Stem Seal Set",
        "category": "Engine",
        "subcategory": "Valvetrain",
        "price_range": (20.00, 80.00),
        "typical_labor_hours": 6.0,
        "common_failure_mileage_range": (100_000, 200_000),
        "is_wear_item": False,
    },
    {
        "name": "Piston Ring Set",
        "category": "Engine",
        "subcategory": "Internal Components",
        "price_range": (60.00, 250.00),
        "typical_labor_hours": 16.0,
        "common_failure_mileage_range": (150_000, 250_000),
        "is_wear_item": False,
    },
    {
        "name": "Connecting Rod Bearing Set",
        "category": "Engine",
        "subcategory": "Internal Components",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 12.0,
        "common_failure_mileage_range": (150_000, 250_000),
        "is_wear_item": False,
    },
    {
        "name": "Main Bearing Set",
        "category": "Engine",
        "subcategory": "Internal Components",
        "price_range": (30.00, 120.00),
        "typical_labor_hours": 14.0,
        "common_failure_mileage_range": (150_000, 250_000),
        "is_wear_item": False,
    },
    {
        "name": "Harmonic Balancer / Crankshaft Pulley",
        "category": "Engine",
        "subcategory": "Belts & Pulleys",
        "price_range": (50.00, 200.00),
        "typical_labor_hours": 1.5,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "EGR Cooler",
        "category": "Exhaust",
        "subcategory": "Emissions",
        "price_range": (200.00, 600.00),
        "typical_labor_hours": 3.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Oxygen Sensor (downstream)",
        "category": "Engine",
        "subcategory": "Sensors",
        "price_range": (50.00, 200.00),
        "typical_labor_hours": 0.8,
        "common_failure_mileage_range": (80_000, 150_000),
        "is_wear_item": True,
    },
    {
        "name": "AC Clutch Assembly",
        "category": "HVAC",
        "subcategory": "Air Conditioning",
        "price_range": (80.00, 250.00),
        "typical_labor_hours": 2.0,
        "common_failure_mileage_range": (80_000, 160_000),
        "is_wear_item": False,
    },
    {
        "name": "Fuel Tank Pressure Sensor",
        "category": "Fuel System",
        "subcategory": "Sensors",
        "price_range": (25.00, 100.00),
        "typical_labor_hours": 0.5,
        "common_failure_mileage_range": (70_000, 150_000),
        "is_wear_item": False,
    },
    {
        "name": "Steering Angle Sensor",
        "category": "Steering",
        "subcategory": "Sensors",
        "price_range": (60.00, 250.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (80_000, 180_000),
        "is_wear_item": False,
    },
    {
        "name": "Transmission Pan Gasket",
        "category": "Transmission",
        "subcategory": "Maintenance",
        "price_range": (15.00, 50.00),
        "typical_labor_hours": 1.0,
        "common_failure_mileage_range": (60_000, 120_000),
        "is_wear_item": True,
    },
]


# ---------------------------------------------------------------------------
# Convenience lookups
# ---------------------------------------------------------------------------

CATEGORIES: list[str] = sorted({p["category"] for p in PARTS})
"""All unique part categories."""

SUBCATEGORIES: dict[str, list[str]] = {}
for _p in PARTS:
    SUBCATEGORIES.setdefault(_p["category"], set()).add(_p["subcategory"])  # type: ignore[arg-type]
SUBCATEGORIES = {k: sorted(v) for k, v in SUBCATEGORIES.items()}  # type: ignore[assignment]
"""Subcategories grouped by category."""

WEAR_ITEMS: list[PartEntry] = [p for p in PARTS if p["is_wear_item"]]
"""All parts classified as normal wear items."""

NON_WEAR_ITEMS: list[PartEntry] = [p for p in PARTS if not p["is_wear_item"]]
"""All parts NOT classified as wear items (failure-based replacements)."""


def get_parts_by_category(category: str) -> list[PartEntry]:
    """Return all parts in a given category (case-insensitive)."""
    return [p for p in PARTS if p["category"].lower() == category.lower()]


def get_parts_by_subcategory(subcategory: str) -> list[PartEntry]:
    """Return all parts in a given subcategory (case-insensitive)."""
    return [
        p for p in PARTS if p["subcategory"].lower() == subcategory.lower()
    ]


def get_parts_in_mileage_range(
    min_miles: int, max_miles: int
) -> list[PartEntry]:
    """Return parts whose common failure range overlaps the given range."""
    return [
        p
        for p in PARTS
        if p["common_failure_mileage_range"][0] <= max_miles
        and p["common_failure_mileage_range"][1] >= min_miles
    ]
