"""Comprehensive vehicle database for synthetic warranty claim generation.

Contains 100+ vehicle entries covering all major US-market makes with
realistic warranty terms, MSRP ranges, engine configurations, and
vehicle classifications. Data reflects 2024-2025 era market conditions.

Sources:
    - Manufacturer warranty documentation (2024-2025 model years)
    - Edmunds, Kelley Blue Book, and J.D. Power pricing data
    - U.S. News & World Report warranty comparisons
"""

from typing import TypedDict


class VehicleEntry(TypedDict):
    """Schema for a vehicle database entry."""

    make: str
    model: str
    years: list[int]
    warranty_bb_months: int        # bumper-to-bumper warranty months
    warranty_bb_miles: int         # bumper-to-bumper warranty miles
    warranty_pt_months: int        # powertrain warranty months
    warranty_pt_miles: int         # powertrain warranty miles
    vehicle_class: str             # sedan, suv, truck, van, sports, luxury
    msrp_range: tuple[int, int]   # (base_price, upper_trim_price)
    engine_types: list[str]        # I4, V6, V8, I6, EV, Hybrid, PHEV, etc.


# ---------------------------------------------------------------------------
# Vehicle database  (100+ entries)
# ---------------------------------------------------------------------------

VEHICLES: list[VehicleEntry] = [

    # ======================================================================
    # FORD  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Ford",
        "model": "F-150",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "truck",
        "msrp_range": (36_000, 78_000),
        "engine_types": ["V6", "V8", "I4 Turbo", "V6 Turbo", "Hybrid", "EV"],
    },
    {
        "make": "Ford",
        "model": "Explorer",
        "years": list(range(2016, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (38_000, 58_000),
        "engine_types": ["I4 Turbo", "V6"],
    },
    {
        "make": "Ford",
        "model": "Escape",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (29_000, 42_000),
        "engine_types": ["I4 Turbo", "Hybrid", "PHEV"],
    },
    {
        "make": "Ford",
        "model": "Mustang",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sports",
        "msrp_range": (32_000, 62_000),
        "engine_types": ["I4 Turbo", "V8"],
    },
    {
        "make": "Ford",
        "model": "Bronco",
        "years": list(range(2021, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (38_000, 56_000),
        "engine_types": ["I4 Turbo", "V6 Turbo"],
    },
    {
        "make": "Ford",
        "model": "Edge",
        "years": list(range(2015, 2025)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (36_000, 50_000),
        "engine_types": ["I4 Turbo", "V6"],
    },

    # ======================================================================
    # CHEVROLET  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Chevrolet",
        "model": "Silverado 1500",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "truck",
        "msrp_range": (38_000, 72_000),
        "engine_types": ["I4 Turbo", "V6", "V8", "I6 Diesel"],
    },
    {
        "make": "Chevrolet",
        "model": "Equinox",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (30_000, 38_000),
        "engine_types": ["I4 Turbo", "EV"],
    },
    {
        "make": "Chevrolet",
        "model": "Malibu",
        "years": list(range(2015, 2025)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (26_000, 34_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "Chevrolet",
        "model": "Traverse",
        "years": list(range(2018, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (36_000, 55_000),
        "engine_types": ["V6", "I4 Turbo"],
    },
    {
        "make": "Chevrolet",
        "model": "Tahoe",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (56_000, 78_000),
        "engine_types": ["V8", "I6 Diesel"],
    },
    {
        "make": "Chevrolet",
        "model": "Colorado",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "truck",
        "msrp_range": (30_000, 48_000),
        "engine_types": ["I4 Turbo", "V6", "I4 Diesel"],
    },
    {
        "make": "Chevrolet",
        "model": "Camaro",
        "years": list(range(2016, 2025)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sports",
        "msrp_range": (30_000, 75_000),
        "engine_types": ["I4 Turbo", "V6", "V8"],
    },

    # ======================================================================
    # TOYOTA  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Toyota",
        "model": "Camry",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (28_000, 36_000),
        "engine_types": ["I4", "Hybrid"],
    },
    {
        "make": "Toyota",
        "model": "RAV4",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (30_000, 42_000),
        "engine_types": ["I4", "Hybrid", "PHEV"],
    },
    {
        "make": "Toyota",
        "model": "Tacoma",
        "years": list(range(2016, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "truck",
        "msrp_range": (31_000, 52_000),
        "engine_types": ["I4", "V6", "I4 Turbo", "Hybrid"],
    },
    {
        "make": "Toyota",
        "model": "Highlander",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (39_000, 52_000),
        "engine_types": ["I4 Turbo", "Hybrid"],
    },
    {
        "make": "Toyota",
        "model": "Corolla",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (23_000, 30_000),
        "engine_types": ["I4", "Hybrid"],
    },
    {
        "make": "Toyota",
        "model": "Tundra",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "truck",
        "msrp_range": (40_000, 75_000),
        "engine_types": ["V6 Turbo", "Hybrid", "V8"],
    },
    {
        "make": "Toyota",
        "model": "4Runner",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (42_000, 58_000),
        "engine_types": ["I4 Turbo", "Hybrid"],
    },

    # ======================================================================
    # HONDA  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Honda",
        "model": "Civic",
        "years": list(range(2016, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (24_000, 32_000),
        "engine_types": ["I4", "I4 Turbo"],
    },
    {
        "make": "Honda",
        "model": "CR-V",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (31_000, 42_000),
        "engine_types": ["I4 Turbo", "Hybrid"],
    },
    {
        "make": "Honda",
        "model": "Accord",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (29_000, 40_000),
        "engine_types": ["I4 Turbo", "Hybrid"],
    },
    {
        "make": "Honda",
        "model": "Pilot",
        "years": list(range(2016, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (39_000, 53_000),
        "engine_types": ["V6", "I4 Turbo"],
    },
    {
        "make": "Honda",
        "model": "Odyssey",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "van",
        "msrp_range": (38_000, 52_000),
        "engine_types": ["V6"],
    },
    {
        "make": "Honda",
        "model": "HR-V",
        "years": list(range(2016, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (25_000, 32_000),
        "engine_types": ["I4"],
    },

    # ======================================================================
    # HYUNDAI  --  5yr/60k BB, 10yr/100k PT
    # ======================================================================
    {
        "make": "Hyundai",
        "model": "Tucson",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (30_000, 40_000),
        "engine_types": ["I4", "Hybrid", "PHEV"],
    },
    {
        "make": "Hyundai",
        "model": "Elantra",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "sedan",
        "msrp_range": (23_000, 32_000),
        "engine_types": ["I4", "Hybrid"],
    },
    {
        "make": "Hyundai",
        "model": "Sonata",
        "years": list(range(2015, 2025)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "sedan",
        "msrp_range": (28_000, 38_000),
        "engine_types": ["I4", "I4 Turbo", "Hybrid"],
    },
    {
        "make": "Hyundai",
        "model": "Santa Fe",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (34_000, 46_000),
        "engine_types": ["I4 Turbo", "Hybrid", "PHEV"],
    },
    {
        "make": "Hyundai",
        "model": "Palisade",
        "years": list(range(2020, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (38_000, 52_000),
        "engine_types": ["V6"],
    },
    {
        "make": "Hyundai",
        "model": "Kona",
        "years": list(range(2018, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (26_000, 36_000),
        "engine_types": ["I4", "EV"],
    },

    # ======================================================================
    # KIA  --  5yr/60k BB, 10yr/100k PT
    # ======================================================================
    {
        "make": "Kia",
        "model": "Telluride",
        "years": list(range(2020, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (37_000, 52_000),
        "engine_types": ["V6"],
    },
    {
        "make": "Kia",
        "model": "Sportage",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (30_000, 40_000),
        "engine_types": ["I4", "I4 Turbo", "Hybrid", "PHEV"],
    },
    {
        "make": "Kia",
        "model": "Forte",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "sedan",
        "msrp_range": (20_000, 26_000),
        "engine_types": ["I4"],
    },
    {
        "make": "Kia",
        "model": "Sorento",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (33_000, 48_000),
        "engine_types": ["I4 Turbo", "V6", "Hybrid", "PHEV"],
    },
    {
        "make": "Kia",
        "model": "K5",
        "years": list(range(2021, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "sedan",
        "msrp_range": (28_000, 36_000),
        "engine_types": ["I4", "I4 Turbo"],
    },
    {
        "make": "Kia",
        "model": "Carnival",
        "years": list(range(2022, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "van",
        "msrp_range": (34_000, 48_000),
        "engine_types": ["V6"],
    },

    # ======================================================================
    # NISSAN  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Nissan",
        "model": "Altima",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (28_000, 36_000),
        "engine_types": ["I4", "I4 Turbo"],
    },
    {
        "make": "Nissan",
        "model": "Rogue",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (30_000, 40_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "Nissan",
        "model": "Sentra",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (22_000, 27_000),
        "engine_types": ["I4"],
    },
    {
        "make": "Nissan",
        "model": "Pathfinder",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (36_000, 52_000),
        "engine_types": ["V6"],
    },
    {
        "make": "Nissan",
        "model": "Frontier",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "truck",
        "msrp_range": (31_000, 42_000),
        "engine_types": ["V6"],
    },

    # ======================================================================
    # BMW  --  4yr/50k BB, 4yr/50k PT  (unified coverage)
    # ======================================================================
    {
        "make": "BMW",
        "model": "3 Series",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (44_000, 60_000),
        "engine_types": ["I4 Turbo", "I6 Turbo"],
    },
    {
        "make": "BMW",
        "model": "5 Series",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (56_000, 78_000),
        "engine_types": ["I6 Turbo", "PHEV", "EV"],
    },
    {
        "make": "BMW",
        "model": "X3",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (48_000, 62_000),
        "engine_types": ["I4 Turbo", "I6 Turbo"],
    },
    {
        "make": "BMW",
        "model": "X5",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (63_000, 88_000),
        "engine_types": ["I6 Turbo", "V8 Turbo", "PHEV"],
    },

    # ======================================================================
    # MERCEDES-BENZ  --  4yr/50k BB, 4yr/50k PT  (unified)
    # ======================================================================
    {
        "make": "Mercedes-Benz",
        "model": "C-Class",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (46_000, 62_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "Mercedes-Benz",
        "model": "E-Class",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (58_000, 82_000),
        "engine_types": ["I4 Turbo", "I6 Turbo"],
    },
    {
        "make": "Mercedes-Benz",
        "model": "GLC",
        "years": list(range(2016, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (48_000, 62_000),
        "engine_types": ["I4 Turbo", "PHEV"],
    },
    {
        "make": "Mercedes-Benz",
        "model": "GLE",
        "years": list(range(2016, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (60_000, 85_000),
        "engine_types": ["I4 Turbo", "I6 Turbo", "V8 Turbo", "PHEV"],
    },

    # ======================================================================
    # AUDI  --  4yr/50k BB, 4yr/50k PT  (unified)
    # ======================================================================
    {
        "make": "Audi",
        "model": "A4",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (42_000, 54_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "Audi",
        "model": "Q5",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (46_000, 60_000),
        "engine_types": ["I4 Turbo", "PHEV"],
    },
    {
        "make": "Audi",
        "model": "Q7",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (58_000, 78_000),
        "engine_types": ["I4 Turbo", "V6 Turbo"],
    },
    {
        "make": "Audi",
        "model": "A6",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (58_000, 72_000),
        "engine_types": ["I4 Turbo", "V6 Turbo"],
    },

    # ======================================================================
    # VOLKSWAGEN  --  4yr/50k BB, 4yr/50k PT  (unified 2024+)
    # ======================================================================
    {
        "make": "Volkswagen",
        "model": "Jetta",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "sedan",
        "msrp_range": (23_000, 31_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "Volkswagen",
        "model": "Tiguan",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "suv",
        "msrp_range": (30_000, 42_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "Volkswagen",
        "model": "Atlas",
        "years": list(range(2018, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "suv",
        "msrp_range": (36_000, 48_000),
        "engine_types": ["I4 Turbo", "V6"],
    },
    {
        "make": "Volkswagen",
        "model": "ID.4",
        "years": list(range(2021, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "suv",
        "msrp_range": (40_000, 52_000),
        "engine_types": ["EV"],
    },

    # ======================================================================
    # SUBARU  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Subaru",
        "model": "Outback",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (31_000, 42_000),
        "engine_types": ["H4", "H4 Turbo"],
    },
    {
        "make": "Subaru",
        "model": "Forester",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (33_000, 42_000),
        "engine_types": ["H4"],
    },
    {
        "make": "Subaru",
        "model": "Crosstrek",
        "years": list(range(2016, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (29_000, 38_000),
        "engine_types": ["H4"],
    },
    {
        "make": "Subaru",
        "model": "Impreza",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (24_000, 30_000),
        "engine_types": ["H4"],
    },

    # ======================================================================
    # MAZDA  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Mazda",
        "model": "CX-5",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (30_000, 42_000),
        "engine_types": ["I4", "I4 Turbo"],
    },
    {
        "make": "Mazda",
        "model": "Mazda3",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (24_000, 36_000),
        "engine_types": ["I4", "I4 Turbo"],
    },
    {
        "make": "Mazda",
        "model": "CX-50",
        "years": list(range(2023, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (31_000, 44_000),
        "engine_types": ["I4", "I4 Turbo"],
    },
    {
        "make": "Mazda",
        "model": "CX-90",
        "years": list(range(2024, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (39_000, 56_000),
        "engine_types": ["I6 Turbo", "PHEV"],
    },

    # ======================================================================
    # DODGE  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Dodge",
        "model": "Charger",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (33_000, 90_000),
        "engine_types": ["I6 Turbo", "V6", "V8"],
    },
    {
        "make": "Dodge",
        "model": "Challenger",
        "years": list(range(2015, 2024)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sports",
        "msrp_range": (32_000, 85_000),
        "engine_types": ["V6", "V8"],
    },
    {
        "make": "Dodge",
        "model": "Durango",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (40_000, 65_000),
        "engine_types": ["V6", "V8"],
    },
    {
        "make": "Dodge",
        "model": "Hornet",
        "years": list(range(2023, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (33_000, 42_000),
        "engine_types": ["I4 Turbo", "PHEV"],
    },

    # ======================================================================
    # RAM  --  3yr/36k BB, 5yr/60k PT  (diesel 5yr/100k PT)
    # ======================================================================
    {
        "make": "Ram",
        "model": "1500",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "truck",
        "msrp_range": (39_000, 78_000),
        "engine_types": ["V6", "V8", "I6 Turbo", "Hybrid"],
    },
    {
        "make": "Ram",
        "model": "2500",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "truck",
        "msrp_range": (42_000, 80_000),
        "engine_types": ["V8", "I6 Diesel"],
    },

    # ======================================================================
    # JEEP  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Jeep",
        "model": "Grand Cherokee",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (40_000, 66_000),
        "engine_types": ["V6", "V8", "I4 Turbo", "PHEV"],
    },
    {
        "make": "Jeep",
        "model": "Wrangler",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (33_000, 58_000),
        "engine_types": ["V6", "I4 Turbo", "PHEV"],
    },
    {
        "make": "Jeep",
        "model": "Cherokee",
        "years": list(range(2015, 2024)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (34_000, 44_000),
        "engine_types": ["I4", "V6", "I4 Turbo"],
    },
    {
        "make": "Jeep",
        "model": "Compass",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (30_000, 40_000),
        "engine_types": ["I4 Turbo"],
    },

    # ======================================================================
    # GMC  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "GMC",
        "model": "Sierra 1500",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "truck",
        "msrp_range": (40_000, 76_000),
        "engine_types": ["I4 Turbo", "V6", "V8", "I6 Diesel"],
    },
    {
        "make": "GMC",
        "model": "Terrain",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (33_000, 40_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "GMC",
        "model": "Acadia",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (38_000, 52_000),
        "engine_types": ["I4 Turbo", "V6"],
    },
    {
        "make": "GMC",
        "model": "Yukon",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (60_000, 82_000),
        "engine_types": ["V8", "I6 Diesel"],
    },

    # ======================================================================
    # CHRYSLER  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Chrysler",
        "model": "Pacifica",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "van",
        "msrp_range": (38_000, 56_000),
        "engine_types": ["V6", "PHEV"],
    },
    {
        "make": "Chrysler",
        "model": "300",
        "years": list(range(2015, 2024)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "sedan",
        "msrp_range": (34_000, 50_000),
        "engine_types": ["V6", "V8"],
    },

    # ======================================================================
    # BUICK  --  3yr/36k BB, 5yr/60k PT
    # ======================================================================
    {
        "make": "Buick",
        "model": "Enclave",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (44_000, 58_000),
        "engine_types": ["V6"],
    },
    {
        "make": "Buick",
        "model": "Encore GX",
        "years": list(range(2020, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (26_000, 34_000),
        "engine_types": ["I3 Turbo", "I4 Turbo"],
    },
    {
        "make": "Buick",
        "model": "Envista",
        "years": list(range(2024, 2026)),
        "warranty_bb_months": 36,
        "warranty_bb_miles": 36_000,
        "warranty_pt_months": 60,
        "warranty_pt_miles": 60_000,
        "vehicle_class": "suv",
        "msrp_range": (24_000, 30_000),
        "engine_types": ["I4 Turbo"],
    },

    # ======================================================================
    # CADILLAC  --  4yr/50k BB, 6yr/70k PT
    # ======================================================================
    {
        "make": "Cadillac",
        "model": "Escalade",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (81_000, 115_000),
        "engine_types": ["V8"],
    },
    {
        "make": "Cadillac",
        "model": "XT5",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (46_000, 56_000),
        "engine_types": ["I4 Turbo", "V6"],
    },
    {
        "make": "Cadillac",
        "model": "CT5",
        "years": list(range(2020, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (38_000, 50_000),
        "engine_types": ["I4 Turbo", "V6 Turbo"],
    },
    {
        "make": "Cadillac",
        "model": "Lyriq",
        "years": list(range(2023, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (58_000, 65_000),
        "engine_types": ["EV"],
    },

    # ======================================================================
    # LINCOLN  --  4yr/50k BB, 6yr/70k PT
    # ======================================================================
    {
        "make": "Lincoln",
        "model": "Aviator",
        "years": list(range(2020, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (56_000, 80_000),
        "engine_types": ["V6 Turbo", "PHEV"],
    },
    {
        "make": "Lincoln",
        "model": "Corsair",
        "years": list(range(2020, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (40_000, 56_000),
        "engine_types": ["I4 Turbo", "PHEV"],
    },
    {
        "make": "Lincoln",
        "model": "Nautilus",
        "years": list(range(2019, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (44_000, 62_000),
        "engine_types": ["I4 Turbo", "I4 Turbo"],
    },
    {
        "make": "Lincoln",
        "model": "Navigator",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (80_000, 112_000),
        "engine_types": ["V6 Turbo"],
    },

    # ======================================================================
    # LEXUS  --  4yr/50k BB, 6yr/70k PT
    # ======================================================================
    {
        "make": "Lexus",
        "model": "RX",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (49_000, 66_000),
        "engine_types": ["I4 Turbo", "Hybrid"],
    },
    {
        "make": "Lexus",
        "model": "ES",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (42_000, 52_000),
        "engine_types": ["I4", "Hybrid"],
    },
    {
        "make": "Lexus",
        "model": "NX",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (40_000, 58_000),
        "engine_types": ["I4 Turbo", "Hybrid", "PHEV"],
    },
    {
        "make": "Lexus",
        "model": "IS",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (40_000, 48_000),
        "engine_types": ["I4 Turbo", "V6"],
    },

    # ======================================================================
    # ACURA  --  4yr/50k BB, 6yr/70k PT
    # ======================================================================
    {
        "make": "Acura",
        "model": "MDX",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (50_000, 66_000),
        "engine_types": ["V6", "V6 Turbo"],
    },
    {
        "make": "Acura",
        "model": "RDX",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (42_000, 52_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "Acura",
        "model": "TLX",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (38_000, 55_000),
        "engine_types": ["I4 Turbo", "V6 Turbo"],
    },
    {
        "make": "Acura",
        "model": "Integra",
        "years": list(range(2023, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "sedan",
        "msrp_range": (33_000, 40_000),
        "engine_types": ["I4 Turbo"],
    },

    # ======================================================================
    # INFINITI  --  4yr/60k BB, 6yr/70k PT
    # ======================================================================
    {
        "make": "Infiniti",
        "model": "QX60",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (50_000, 62_000),
        "engine_types": ["V6", "I4 Turbo"],
    },
    {
        "make": "Infiniti",
        "model": "QX80",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (72_000, 92_000),
        "engine_types": ["V8", "V6 Turbo"],
    },
    {
        "make": "Infiniti",
        "model": "QX50",
        "years": list(range(2019, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (40_000, 52_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "Infiniti",
        "model": "Q50",
        "years": list(range(2015, 2025)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 72,
        "warranty_pt_miles": 70_000,
        "vehicle_class": "luxury",
        "msrp_range": (42_000, 56_000),
        "engine_types": ["V6 Turbo"],
    },

    # ======================================================================
    # VOLVO  --  4yr/50k BB, 4yr/50k PT
    # ======================================================================
    {
        "make": "Volvo",
        "model": "XC60",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (46_000, 60_000),
        "engine_types": ["I4 Turbo", "PHEV"],
    },
    {
        "make": "Volvo",
        "model": "XC90",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (58_000, 82_000),
        "engine_types": ["I4 Turbo", "PHEV"],
    },
    {
        "make": "Volvo",
        "model": "XC40",
        "years": list(range(2019, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (38_000, 48_000),
        "engine_types": ["I4 Turbo", "EV"],
    },
    {
        "make": "Volvo",
        "model": "S60",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 48,
        "warranty_pt_miles": 50_000,
        "vehicle_class": "luxury",
        "msrp_range": (42_000, 54_000),
        "engine_types": ["I4 Turbo", "PHEV"],
    },

    # ======================================================================
    # GENESIS  --  5yr/60k BB, 10yr/100k PT
    # ======================================================================
    {
        "make": "Genesis",
        "model": "G70",
        "years": list(range(2019, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "luxury",
        "msrp_range": (42_000, 56_000),
        "engine_types": ["I4 Turbo", "V6 Turbo"],
    },
    {
        "make": "Genesis",
        "model": "G80",
        "years": list(range(2017, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "luxury",
        "msrp_range": (54_000, 72_000),
        "engine_types": ["I4 Turbo", "V6 Turbo", "EV"],
    },
    {
        "make": "Genesis",
        "model": "GV70",
        "years": list(range(2022, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "luxury",
        "msrp_range": (44_000, 62_000),
        "engine_types": ["I4 Turbo", "V6 Turbo", "EV"],
    },
    {
        "make": "Genesis",
        "model": "GV80",
        "years": list(range(2021, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "luxury",
        "msrp_range": (54_000, 76_000),
        "engine_types": ["I4 Turbo", "V6 Turbo"],
    },

    # ======================================================================
    # MITSUBISHI  --  5yr/60k BB, 10yr/100k PT
    # ======================================================================
    {
        "make": "Mitsubishi",
        "model": "Outlander",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (30_000, 42_000),
        "engine_types": ["I4", "PHEV"],
    },
    {
        "make": "Mitsubishi",
        "model": "Outlander Sport",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (25_000, 32_000),
        "engine_types": ["I4"],
    },
    {
        "make": "Mitsubishi",
        "model": "Eclipse Cross",
        "years": list(range(2018, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "suv",
        "msrp_range": (28_000, 36_000),
        "engine_types": ["I4 Turbo"],
    },
    {
        "make": "Mitsubishi",
        "model": "Mirage",
        "years": list(range(2015, 2025)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 120,
        "warranty_pt_miles": 100_000,
        "vehicle_class": "sedan",
        "msrp_range": (17_000, 21_000),
        "engine_types": ["I3"],
    },

    # ======================================================================
    # TESLA  --  4yr/50k BB, 8yr/100-150k PT (battery/drivetrain)
    # ======================================================================
    {
        "make": "Tesla",
        "model": "Model 3",
        "years": list(range(2018, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 96,
        "warranty_pt_miles": 120_000,
        "vehicle_class": "sedan",
        "msrp_range": (39_000, 54_000),
        "engine_types": ["EV"],
    },
    {
        "make": "Tesla",
        "model": "Model Y",
        "years": list(range(2020, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 96,
        "warranty_pt_miles": 120_000,
        "vehicle_class": "suv",
        "msrp_range": (44_000, 58_000),
        "engine_types": ["EV"],
    },
    {
        "make": "Tesla",
        "model": "Model S",
        "years": list(range(2015, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 96,
        "warranty_pt_miles": 150_000,
        "vehicle_class": "luxury",
        "msrp_range": (75_000, 110_000),
        "engine_types": ["EV"],
    },
    {
        "make": "Tesla",
        "model": "Model X",
        "years": list(range(2016, 2026)),
        "warranty_bb_months": 48,
        "warranty_bb_miles": 50_000,
        "warranty_pt_months": 96,
        "warranty_pt_miles": 150_000,
        "vehicle_class": "luxury",
        "msrp_range": (80_000, 120_000),
        "engine_types": ["EV"],
    },

    # ======================================================================
    # RIVIAN  --  5yr/60k BB, 8yr/175k PT
    # ======================================================================
    {
        "make": "Rivian",
        "model": "R1T",
        "years": list(range(2022, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 96,
        "warranty_pt_miles": 175_000,
        "vehicle_class": "truck",
        "msrp_range": (73_000, 95_000),
        "engine_types": ["EV"],
    },
    {
        "make": "Rivian",
        "model": "R1S",
        "years": list(range(2022, 2026)),
        "warranty_bb_months": 60,
        "warranty_bb_miles": 60_000,
        "warranty_pt_months": 96,
        "warranty_pt_miles": 175_000,
        "vehicle_class": "suv",
        "msrp_range": (76_000, 98_000),
        "engine_types": ["EV"],
    },
]


# ---------------------------------------------------------------------------
# Convenience lookups
# ---------------------------------------------------------------------------

MAKES: list[str] = sorted({v["make"] for v in VEHICLES})
"""All unique manufacturer names in the database."""

VEHICLE_CLASSES: list[str] = sorted({v["vehicle_class"] for v in VEHICLES})
"""All unique vehicle classifications."""

ENGINE_TYPES: list[str] = sorted(
    {et for v in VEHICLES for et in v["engine_types"]}
)
"""All unique engine type designations."""


def get_vehicles_by_make(make: str) -> list[VehicleEntry]:
    """Return all vehicles for a given make (case-insensitive)."""
    return [v for v in VEHICLES if v["make"].lower() == make.lower()]


def get_vehicles_by_class(vehicle_class: str) -> list[VehicleEntry]:
    """Return all vehicles for a given class (sedan, suv, truck, etc.)."""
    return [
        v for v in VEHICLES if v["vehicle_class"].lower() == vehicle_class.lower()
    ]


def get_warranty_terms(make: str) -> dict[str, int]:
    """Return representative warranty terms for a make.

    Uses the first matching vehicle's terms as representative.
    Returns empty dict if make is not found.
    """
    vehicles = get_vehicles_by_make(make)
    if not vehicles:
        return {}
    v = vehicles[0]
    return {
        "bb_months": v["warranty_bb_months"],
        "bb_miles": v["warranty_bb_miles"],
        "pt_months": v["warranty_pt_months"],
        "pt_miles": v["warranty_pt_miles"],
    }
